[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "acgen"
version = "0.0.1"
dependencies = [
    "paramiko==3.5.0",
    "Requests==2.32.3",
    "scp==0.15.0",
]

[tool.setuptools.packages.find]
where = ["acgen"]